galaxy_info:
  author: Vend Vahk
  description: Sample role
  company: none
  platforms:
    - name: EL
      versions:
        - any
    - name: Debian
      versions:
        - any
    - name: Ubuntu
      versions:
        - any

  license: BSD-3-Clause

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
